name: Sync Leetcode

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 8 * * 6" # Runs automatically every Saturday at 8:00 AM

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Solutions
        uses: joshcai/leetcode-sync@v1.5
        env:
          
          GIT_AUTHOR_NAME: "ARYISTA"
          GIT_AUTHOR_EMAIL: "202307020014@karnavatiuniversity.edu.in"
          GIT_COMMITTER_NAME: "ARYISTA"
          GIT_COMMITTER_EMAIL: "202307020014@karnavatiuniversity.edu.in"
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: leetcode-problems
